---
apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: druid
spec:
  image:
    productVersion: 24.0.0
    stackableVersion: "23.1"
  clusterConfig:
    zookeeperConfigMapName: druid-znode
    metadataStorageDatabase:
      dbType: postgresql
      connString: jdbc:postgresql://postgresql-druid/druid
      host: postgresql-druid
      port: 5432
      user: druid
      password: druid
    deepStorage:
      s3:
        bucket:
          inline:
            bucketName: druid
            connection:
              inline:
                host: minio-druid
                port: 9000
                accessStyle: Path
                credentials:
                  secretClass: druid-s3-credentials
        baseKey: data
  brokers:
    roleGroups:
      default:
        replicas: 1
  coordinators:
    roleGroups:
      default:
        replicas: 1
  historicals:
    roleGroups:
      default:
        replicas: 2
        config:
          resources:
            cpu:
              min: "1"
              max: "2"
            memory:
              limit: 2Gi # TODO Increase with 23.4
            storage:
              segmentCache:
                emptyDir:
                  capacity: 8Gi
        # configOverrides:
        #   runtime.properties:
        #     druid.processing.numThreads: "2" # TODO Can be removed with 23.4 as we have a strategy how to derive this setting from the configured resources
  middleManagers:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              min: "1"
              max: "4" # Need enough CPU cores to run multiple ingestion jobs at once
  routers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: druid-znode
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: druid-s3-credentials
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: druid-s3-credentials
  labels:
    secrets.stackable.tech/class: druid-s3-credentials
stringData:
  accessKey: druid
  secretKey: druiddruid
