---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: kafka-znode
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: "23.7"
  clusterConfig:
    zookeeperConfigMapName: kafka-znode
    authentication:
      - authenticationClass: kafka-client-tls
  brokers:
    config:
      resources:
        storage:
          logDirs:
            capacity: 30Gi
        cpu:
          max: 500m
          min: 250m
        memory:
          limit: 2Gi
    roleGroups:
      default:
        replicas: 1
        configOverrides:
          server.properties:
            num.partitions: "8"
            # We have
            # 1 brokers
            # and 2 topics (with 8 partitions)
            # 30Gi pvc * 1 brokers = 30Gi total disk size.
            # Lets aim for 50% => 0.5 * 8Gi = 15Gi / 16 partitions = 0.9375Gi
            log.segment.bytes: "100000000" # 0.1 GB
            log.retention.bytes: "900000000" # 0.9 GB. Should keep between 0.9 and 1.0 GB
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: kafka-client-tls
spec:
  provider:
    tls:
      clientCertSecretClass: tls
