releaseName: prometheus
name: kube-prometheus-stack
repo:
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
version: 41.9.1
options:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
    service:
      type: NodePort
      nodePort: null
  grafana:
    adminPassword: {{ grafanaAdminPassword }}
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: NodePort
      nodePort: null
  kube-state-metrics:
    metricLabelsAllowlist:
      - pods=[*]
      - statefulsets=[*]
      - service=[*]
      - nodes=[*]
      - namespaces=[*]
      - configmaps=[*]
