releaseName: prometheus
name: kube-prometheus-stack
repo:
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
version: 48.1.1
options:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi
    service:
      type: NodePort
      nodePort: null
  grafana:
    grafana.ini:
      analytics:
        check_for_updates: false
    adminPassword: {{ grafanaAdminPassword }}
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: NodePort
      nodePort: null
    dashboardProviders:
      stackable-dashboardprovider.yaml:
        apiVersion: 1
        providers:
        - name: 'stackable'
          orgId: 1
          folder: 'Stackable Data Platform'
          type: file
          disableDeletion: false
          allowUiUpdates: true # TODO set to false. Is enabled so Dashboards can be build easier. Note: If a provisioned dashboard is saved from the UI and then later updated from the source, the dashboard stored in the database will always be overwritten
          options:
            path: /var/lib/grafana/dashboards/stackable # Must be /var/lib/grafana/dashboards/<provider_name>
    dashboardsConfigMaps:
      stackable: stackable-grafana-dashboards
  kube-state-metrics:
    metricLabelsAllowlist:
      - pods=[*]
      - statefulsets=[*]
      - services=[*]
      - nodes=[*]
      - namespaces=[*]
      - namespaces=[*]
      - configmaps=[*]
      - persistentvolumes=[*]
      - persistentvolumeclaims=[*]
