---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-iceberg
spec:
  version: 3.1.3-stackable0.2.0
  s3:
    reference: minio
  metastore:
    roleGroups:
      default:
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://postgresql-hive-iceberg:5432/hive
            user: hive
            password: hive
            dbType: postgres
