[package]
name = "stackablectl"
description = "Command line tool to interact with a Stackable Data Platform"
authors = ["Stackable GmbH <info@stackable.de>"]
version = "0.2.0"
edition = "2021"
license = "OSL-3.0"
repository = "https://github.com/stackabletech/stackablecrt"

[dependencies]
cached = "0.34"
clap = { version = "3.2", features = ["derive", "cargo"] }
env_logger = "0.9"
indexmap = { version = "1.8", features = ["serde"] }
k8s-openapi = { version = "0.15.0", default-features = false, features = ["v1_24"] }
kube = { version = "0.73.1", default-features = false, features = ["client", "rustls-tls"] }
lazy_static = "1.4"
log = "0.4"
which = "4.2"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
tokio = "1.19.2"

[profile.release]
# strip = true # By default on Linux and macOS, symbol information is included in the compiled .elf file.
lto = true # Enable Link Time Optimization to reduce binary size

[build-dependencies]
gobuild = "0.1.0-alpha.2"
