---
apiVersion: batch/v1
kind: Job
metadata:
    name: prepare-minio-load-jar
spec:
    template:
        spec:
            containers:
                - name: prepare-minio-load-jar
                  image: "bitnami/minio:2022-debian-10"
                  command: ["bash", "-c", "cd /tmp && curl -O https://repo.stackable.tech/repository/misc/hbase-spark-k8s/sparkHbaseAccess-1.0-SNAPSHOT.jar && mc --insecure alias set minio http://minio-spark:9000 demo-minio demodemo && mc cp sparkHbaseAccess-1.0-SNAPSHOT.jar minio/demo/hbase-hdfs-cycling-data/lib/"]
            restartPolicy: OnFailure
    backoffLimit: 50

