---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark-hbase-connection
spec:
  version: "1.0"
  sparkImage: docker.stackable.tech/stackable/spark-k8s:3.3.0-stackable0.99.0 #local ARM version
  sparkImagePullPolicy: IfNotPresent
  mode: cluster
  mainClass: tech.stackable.demo.spark.tbd
  mainApplicationFile: tbd
  volumes:
    - name: config-volume-hbase
      configMap:
        name: hbase-master-default
  args:
    - "--input /arguments/hbase-site.xml"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    volumeMounts:
      - name: config-volume-hbase
        mountPath: /arguments
    nodeSelector:
      node: "1"
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    volumeMounts:
      - name: config-volume-hbase
        mountPath: /arguments
    nodeSelector:
      node: "1"


