---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark-hbase-connection
spec:
  version: "1.0"
  sparkImage: docker.stackable.tech/stackable/spark-k8s:3.3.0-stackable0.2.0
  sparkImagePullPolicy: IfNotPresent
  mode: cluster
  mainClass: tech.stackable.demo.spark.scan
  mainApplicationFile: s3a://my-bucket/hbase-hdfs-cycling-data/lib/sparkHbaseAccess-1.0-SNAPSHOT.jar
  s3bucket:
    inline:
      bucketName: my-bucket
      connection:
        inline:
          host: demo-minio
          port: 9000
          accessStyle: Path
          credentials:
            secretClass: s3-credentials-class
  sparkConf:
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
  volumes:
    - name: config-volume-hbase
      configMap:
        name: hbase-master-default
  args:
    - "--hbaseSite /arguments/hbase-site.xml"
    - "--tableName cycling-tripdata"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    volumeMounts:
      - name: config-volume-hbase
        mountPath: /arguments
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    volumeMounts:
      - name: config-volume-hbase
        mountPath: /arguments