---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
    stackableVersion: "23.7"
  clusterConfig:
    vectorAggregatorConfigMapName: vector-aggregator-discovery
  servers:
    roleGroups:
      default:
        replicas: 3
        config:
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: WARN
              zookeeper:
                console:
                  level: INFO
                file:
                  level: INFO
                loggers:
                  ROOT:
                    level: INFO
                  org.apache.zookeeper.server.NettyServerCnxn:
                    level: NONE
