---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  version: 3.8.0-stackable0.8.0
  vectorAggregatorConfigMapName: vector-aggregator-discovery
  servers:
    roleGroups:
      default:
        replicas: 3
        config:
          logging:
            enableVectorAgent: true
            containers:
              vector:
                console:
                  levelThreshold: INFO
                file:
                  levelThreshold: WARN
              zookeeper:
                loggers:
                  ROOT:
                    level: INFO
                  org.apache.zookeeper.server.NettyServerCnxn:
                    level: WARN
