---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: hbase
spec:
  image:
    custom: docker.stackable.tech/stackable/hbase:2.4.12-stackable0.2.0-jmx-dns-snappy
    productVersion: 2.4.12
  hdfsConfigMapName: hdfs
  zookeeperConfigMapName: hbase-znode
  config:
    hbaseRootdir: /hbase
  masters:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: "1"
          max: "1"
        memory:
          limit: 4Gi
  regionServers:
    roleGroups:
      default:
        replicas: 13
    config:
      resources:
        cpu:
          min: "3500m"
          max: "6"
        memory:
          limit: 20Gi
    configOverrides:
      # hbase-env.sh:
      #   HBASE_OFFHEAPSIZE: 12G
      hbase-site.xml:
        hbase.regionserver.handler.count: "100"

        # hbase.regionserver.global.memstore.size: "0.59"
        # hbase.regionserver.global.memstore.size.lower.limit: "0.58"
        # hbase.hregion.memstore.flush.size: "134217728" # default

        # hbase.bucketcache.ioengine: offheap
        # hfile.block.cache.size: "0.2"
        # hbase.bucketcache.size: "4196" # measured in mb
  restServers:
    roleGroups:
      default:
        replicas: 0
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 2Gi
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hbase-znode
spec:
  clusterRef:
    name: zookeeper
