---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: hbase
spec:
  version: 2.4.12-stackable0.2.0-jmx-conf # 2.4.12-stackable0.2.0
  hdfsConfigMapName: hdfs
  zookeeperConfigMapName: hbase-znode
  config:
    hbaseRootdir: /hbase
  masters:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: "1"
          max: "1"
        memory:
          limit: 4Gi
  regionServers:
    roleGroups:
      default:
        replicas: 9
    config:
      resources:
        cpu:
          min: "5"
          max: "6"
        memory:
          limit: 22Gi
  restServers:
    roleGroups:
      default:
        replicas: 0
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 2Gi
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hbase-znode
spec:
  clusterRef:
    name: zookeeper
