apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
  image:
    productVersion: 3.3.4
    # stackableVersion: "23.1" # Use instead of custom when dns problem is fixed
    custom: docker.stackable.tech/stackable/hadoop:3.3.4-stackable0.1.0-dns-fix
  zookeeperConfigMapName: hdfs-znode
  dfsReplication: 3
  journalNodes:
    roleGroups:
      default:
        replicas: 1
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 2Gi
        storage:
          data:
            capacity: 3Gi
            # storageClass: premium-rwo # Comment out if not running on GKE
  nameNodes:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: "1"
          max: "1"
        memory:
          limit: 4Gi
        storage:
          data:
            capacity: 3Gi
            # storageClass: premium-rwo # Comment out if not running on GKE
  dataNodes:
    roleGroups:
      default:
        replicas: 13
    config:
      resources:
        cpu:
          min: "2"
          max: "2"
        memory:
          limit: 2Gi
        storage:
          data:
            capacity: 20Gi
            # storageClass: premium-rwo # Comment out if not running on GKE
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hdfs-znode
spec:
  clusterRef:
    name: zookeeper
