apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
  version: 3.3.4-stackable0.1.0-dns-fix
  zookeeperConfigMapName: hdfs-znode
  dfsReplication: 3
  journalNodes:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 2Gi
        storage:
          data:
            capacity: 3Gi
            storageClass: premium-rwo
  nameNodes:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: "1"
          max: "1"
        memory:
          limit: 4Gi
        storage:
          data:
            capacity: 3Gi
            storageClass: premium-rwo
  dataNodes:
    roleGroups:
      default:
        replicas: 13
    config:
      resources:
        cpu:
          min: "2"
          max: "2"
        memory:
          limit: 2Gi
        storage:
          data:
            capacity: 20Gi
            storageClass: premium-rwo
  log4j: |-
    # Define some default values that can be overridden by system properties
    hadoop.root.logger=INFO,console
    hadoop.log.dir=.
    hadoop.log.file=hadoop.log
    # Define the root logger to the system property "hadoop.root.logger".
    log4j.rootLogger=${hadoop.root.logger}, EventCounter
    # Logging Threshold
    log4j.threshold=ALL
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.target=System.err
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{ISO8601} %p %c{2}: %m%n
    log4j.appender.EventCounter=org.apache.hadoop.log.metrics.EventCounter
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hdfs-znode
spec:
  clusterRef:
    name: zookeeper
