apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
  version: 3.3.3-stackable0.1.0
  zookeeperConfigMapName: hdfs-znode
  dfsReplication: 3
  journalNodes:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 2Gi
        storage:
          data:
            capacity: 5Gi
  nameNodes:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 2Gi
        storage:
          data:
            capacity: 5Gi
  dataNodes:
    roleGroups:
      default:
        replicas: 5
    config:
      resources:
        cpu:
          min: 500m
          max: 500m
        memory:
          limit: 5Gi
        storage:
          data:
            capacity: 25Gi
  log4j: |-
    # Define some default values that can be overridden by system properties
    hadoop.root.logger=INFO,console
    hadoop.log.dir=.
    hadoop.log.file=hadoop.log
    # Define the root logger to the system property "hadoop.root.logger".
    log4j.rootLogger=${hadoop.root.logger}, EventCounter
    # Logging Threshold
    log4j.threshold=ALL
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.target=System.err
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{ISO8601} %p %c{2}: %m%n
    log4j.appender.EventCounter=org.apache.hadoop.log.metrics.EventCounter
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hdfs-znode
spec:
  clusterRef:
    name: zookeeper
