---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  version: 3.8.0-stackable0.7.1
  config:
    quorumTlsSecretClass: tls # Todo disable quorum tls
  servers:
    roleGroups:
      default:
        replicas: 3
    config:
      resources:
        cpu:
          min: 500m
          max: 500m
        memory:
          limit: 512Mi
        storage:
          data:
            capacity: 1Gi
            storageClass: premium-rwo
