---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  image:
    productVersion: 3.8.0
    # stackableVersion: "23.1" # Use instead of custom when dns problem is fixed
    custom: docker.stackable.tech/stackable/zookeeper:3.8.0-stackable0.7.1-dns-fix
  servers:
    roleGroups:
      default:
        replicas: 3
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 512Mi
        storage:
          data:
            capacity: 1Gi
            # storageClass: premium-rwo # Comment out if not running on GKE
