---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  version: 2.2.5-python39-stackable0.3.0
  statsdExporterVersion: v0.22.4
  executor: CeleryExecutor
  loadExamples: false
  exposeConfig: false
  credentialsSecret: airflow-credentials
  volumes:
    - name: airflow-dags
      configMap:
        name: airflow-dags
  volumeMounts:
    - name: airflow-dags
      mountPath: /dags/date_demo.py
      subPath: date_demo.py
  webservers:
    roleGroups:
      default:
        envOverrides:
          AIRFLOW__CORE__DAGS_FOLDER: "/dags"
        replicas: 1
  workers:
    roleGroups:
      default:
        envOverrides:
          AIRFLOW__CORE__DAGS_FOLDER: "/dags"
        replicas: 2
  schedulers:
    roleGroups:
      default:
        envOverrides:
          AIRFLOW__CORE__DAGS_FOLDER: "/dags"
        replicas: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-dags
data:
  date_demo.py: |
    """Example DAG returning the current date"""
    from datetime import datetime, timedelta

    from airflow import DAG
    from airflow.operators.bash import BashOperator

    with DAG(
        dag_id='date_demo',
        schedule_interval='0-59 * * * *',
        start_date=datetime(2021, 1, 1),
        catchup=False,
        dagrun_timeout=timedelta(minutes=5),
        tags=['example'],
        params={},
    ) as dag:

        run_this = BashOperator(
            task_id='run_every_minute',
            bash_command='date',
        )
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-credentials
type: Opaque
stringData:
  adminUser.username: airflow
  adminUser.firstname: Airflow
  adminUser.lastname: Admin
  adminUser.email: airflow@airflow.com
  adminUser.password: airflow
  connections.secretKey: thisISaSECRET_1234
  connections.sqlalchemyDatabaseUri: postgresql+psycopg2://airflow:airflow@postgresql-airflow/airflow
  connections.celeryResultBackend: db+postgresql://airflow:airflow@postgresql-airflow/airflow
  connections.celeryBrokerUrl: redis://:airflow@redis-airflow-master:6379/0
