---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: openldap
spec:
  provider:
    ldap:
      hostname: openldap.default.svc.cluster.local
      searchBase: ou=users,dc=example,dc=org
      # The bind credentials are used so an application can bind to the LDAP server
      bindCredentials:
        secretClass: ldap-bind-credentials
      port: 1636
      tls:
        verification:
          server:
            caCert:
              secretClass: openldap-tls

---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: openldap-bind-credentials
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-bind-credentials
  labels:
    secrets.stackable.tech/class: openldap-bind-credentials
stringData:
  # User and password are defined in the OpenLDAP StatefulSet
  user: cn=ldapadmin,dc=example,dc=org
  password: ldapadminpassword