= Installation

== Pre-compiled binary
We ship pre-compiled binaries of `stackablectl` which should work on most environments such as Windows, macOS, and Linux distros like Ubuntu and Arch.

Below are the installation instructions for <<Linux>>, <<macOS>> and <<Windows>>.
If the binary does not work for you, you can always <<_build_stackablectl_from_source>>

=== Linux

Download the `stackablectl-x86_64-unknown-linux-gnu` binary file from the link:https://github.com/stackabletech/stackablectl/releases/latest[latest release], then rename the file to `stackabelctl`:

[source,console]
----
$ mv stackablectl-x86_64-unknown-linux-gnu stackablectl
----

and mark it as executable:

[source,console]
----
$ chmod +x stackablectl
----

You can now invoke it with:

[source,console]
----
$ ./stackablectl
----

If you want to be able to call it from everywhere (not only the directory you downloaded it to) you can add it to your system with the following command:

[source,console]
----
$ sudo mv stackablectl /usr/bin/stackablectl
----

=== Windows

Download `stackablectl-x86_64-pc-windows-gnu.exe` from the link:https://github.com/stackabletech/stackablectl/releases/latest[latest release].
You can simply execute it.
If you want to execute it from anywhere in your system, you need to add it to the system `PATH`.

=== macOS
Download the `stackablectl-x86_64-apple-darwin` binary file for Intel based Macs or  `stackablectl-aarch64-apple-darwin` binary file for ARM based Macs from the link:https://github.com/stackabletech/stackablectl/releases/latest[latest release].
Then rename the file to `stackablectl`:

[source,console]
----
$ mv stackablectl-x86_64-apple-darwin stackablectl
# or
$ mv stackablectl-aarch64-apple-darwin stackablectl
----

and mark it as executable:

[source,console]
----
$ chmod +x stackablectl
----

You can now invoke it with:

[source,console]
----
$ ./stackablectl
----

If macOS denies the execution of stackablectl go to `Settings` -> `Security & Privacy` -> `General`. Here you will see a pop up asking if you want to allow access for `stackablectl`. You must allow access.

== Build stackablectl from source
To build `stackablectl` from source you need to have the following tools installed:

* Rust compiler
** Needed for compiling source code of `stackablectl` itself
* Go compiler
** Needed for compiling a wrapper around the Go lib `go-helm-client`
* C compiler
** As we use the vendored feature of the https://crates.io/crates/openssl[openssl crate] a C compiler is needed to compile openssl from source
* Perl
** As we use the vendored feature of the https://crates.io/crates/openssl[openssl crate] perl is needed to compile openssl from source
* Make
** As we use the vendored feature of the https://crates.io/crates/openssl[openssl crate] Make is needed to compile openssl from source

If you have the required tools available, you need to clone the `stackablectl` repo https://github.com/stackabletech/stackablectl and invoke the build with

[source,console]
----
$ cargo build --release
----

After a successful build the binary will be placed in `target/release/stackablectl`.
Copy it to your systems path to access it from anywhere if you like.

[source,console]
----
$ sudo cp target/release/stackablectl /usr/bin/stackablectl 
----

== Configure auto-completion
`stackablectl` provides completion scripts for the major shells out there.
It uses the same mechanism as `kubectl` does, so if you have any problems following this steps looking at https://kubernetes.io/docs/tasks/tools/included/[their installation documentation] may help you out.

All of the https://docs.rs/clap_complete/3.2.3/clap_complete/shells/enum.Shell.html[supported shells of] https://crates.io/crates/clap_complete[`clap_complete`] are supported.
As of `07/2022` this includes the following shells:

* <<Bash>>
* Elvish
* <<Fish>>
* <<PowerShell>>
* <<Zsh>>

=== Bash
The stackablectl completion script for Bash can be generated with the command `stackablectl completion bash`. Sourcing the completion script in your shell enables stackablectl autocompletion.

Install the package `bash-completion` e.g. via `apt install bash-completion`.

After that run the following command to source the completion script and tell bash to source it every time you start a new shell.

[source,console]
----
$ source <(stackablectl completion bash)
$ echo 'source <(stackablectl completion bash)' >> ~/.bashrc
----

=== Fish
The stackablectl completion script for Fish can be generated with the command `stackablectl completion fish`. Sourcing the completion script in your shell enables stackablectl autocompletion.

[source,console]
----
$ stackablectl completion fish | source
$ echo 'stackablectl completion fish | source' >> ~/.config/fish/config.fish
----

=== PowerShell
The stackablectl completion script for PowerShell can be generated with the command `stackablectl completion powershell`.

To do so in all your shell sessions, add the following line to your `$PROFILE` file:

[source,console]
----
kubectl completion powershell | Out-String | Invoke-Expression
----

This command will regenerate the auto-completion script on every PowerShell start up.

=== Zsh
The stackablectl completion script for Zsh can be generated with the command `stackablectl completion zsh`. Sourcing the completion script in your shell enables stackablectl autocompletion.

[source,console]
----
$ source <(stackablectl completion zsh)
$ echo 'source <(stackablectl completion zsh)' >> ~/.zshrc
----
