---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-ny-taxi-data-table-in-trino
spec:
  template:
    spec:
      containers:
        - name: create-ny-taxi-data-table-in-trino
          image: docker.stackable.tech/stackable/testing-tools:0.1.0-stackable0.1.0
          command: ["bash", "-c", "python -u /tmp/script/script.py"]
          volumeMounts:
            - name: script
              mountPath: /tmp/script
            - name: trino-users
              mountPath: /trino-users
      volumes:
        - name: script
          configMap:
            name: create-ny-taxi-data-table-in-trino-script
        - name: trino-users
          secret:
            secretName: trino-users
      restartPolicy: OnFailure
  backoffLimit: 50
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-ny-taxi-data-table-in-trino-script
data:
  script.py: |
    import sys
    import trino

    if not sys.warnoptions:
        import warnings
    warnings.simplefilter("ignore")

    def get_connection():
        connection = trino.dbapi.connect(
            host="trino-coordinator",
            port=8443,
            user="admin",
            http_scheme='https',
            auth=trino.auth.BasicAuthentication("admin", open("/trino-users/admin").read()),
        )
        connection._http_session.verify = False
        return connection

    def run_query(connection, query):
        print(f"[DEBUG] Executing query {query}")
        cursor = connection.cursor()
        cursor.execute(query)
        return cursor.fetchall()

    connection = get_connection()

    run_query(connection, "CREATE SCHEMA IF NOT EXISTS hive.demo WITH (location = 's3a://demo/')")
    run_query(connection, """
        CREATE TABLE IF NOT EXISTS hive.demo.ny_taxi_data_raw (
            VendorID BIGINT,
            tpep_pickup_datetime TIMESTAMP,
            tpep_dropoff_datetime TIMESTAMP,
            passenger_count DOUBLE,
            trip_distance DOUBLE,
            payment_type BIGINT,
            Fare_amount DOUBLE,
            Tip_amount DOUBLE,
            Total_amount DOUBLE
        ) WITH (
            external_location = 's3a://demo/ny-taxi-data/raw/',
            format = 'parquet'
        )
    """)

    loaded_rows = run_query(connection, "SELECT COUNT(*) FROM hive.demo.ny_taxi_data_raw")[0][0]
    print(f"Loaded {loaded_rows} rows")
    assert loaded_rows > 0

    print("Analyzing table ny_taxi_data_raw")
    analyze_rows = run_query(connection, """ANALYZE hive.demo.ny_taxi_data_raw""")[0][0]
    assert analyze_rows == loaded_rows
    stats = run_query(connection, """show stats for hive.demo.ny_taxi_data_raw""")
    print("Produced the following stats:")
    print(*stats, sep="\n")

    run_query(connection, """
        create or replace view hive.demo.ny_taxi_data as
        select
          vendorid,
          tpep_pickup_datetime,
          tpep_dropoff_datetime,
          date_diff('minute', tpep_pickup_datetime, tpep_dropoff_datetime) as duration_min,
          passenger_count,
          trip_distance,
          case payment_type when 1 then 'Credit card' when 2 then 'Cash' when 3 then 'No charge' when 4 then 'Dispute' when 6 then 'Voided trino' else 'Unknown' end as payment_type,
          fare_amount,
          tip_amount,
          total_amount
        from hive.demo.ny_taxi_data_raw
        where tpep_pickup_datetime >= from_iso8601_timestamp('2019-12-01T00:00:00')
        and tpep_pickup_datetime <= from_iso8601_timestamp('2022-05-31T00:00:00')
    """)

    rows_in_view = run_query(connection, "SELECT COUNT(*) FROM hive.demo.ny_taxi_data")[0][0]
    print(f"{rows_in_view} rows in view")
    assert rows_in_view > 0
