---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-ny-taxi-data
spec:
  template:
    spec:
      containers:
        - name: load-ny-taxi-data
          image: "bitnami/minio:2022-debian-10"
          command: ["bash", "-c", "cd /tmp && for month in 2020-01 2020-02 2020-03 2020-04 2020-05 2020-06 2020-07 2020-08 2020-09 2020-10 2020-11 2020-12 2021-01 2021-02 2021-03 2021-04 2021-05 2021-06 2021-07 2021-08 2021-09 2021-10 2021-11 2021-12 2022-01 2022-02 2022-03 2022-04; do curl -O https://repo.stackable.tech/repository/misc/ny-taxi-data/yellow_tripdata_$month.parquet && mc --insecure alias set minio http://minio:9000/ $(cat /minio-s3-credentials/accessKey) $(cat /minio-s3-credentials/secretKey) && mc cp yellow_tripdata_$month.parquet minio/demo/ny-taxi-data/raw/; done"]
          volumeMounts:
            - name: minio-s3-credentials
              mountPath: /minio-s3-credentials
      volumes:
        - name: minio-s3-credentials
          secret:
            secretName: minio-s3-credentials
      restartPolicy: OnFailure
  backoffLimit: 50
