---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: kafka-znode
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka
spec:
  image:
    productVersion: 3.4.0
    stackableVersion: "23.7"
  clusterConfig:
    zookeeperConfigMapName: kafka-znode
    authentication:
      - authenticationClass: kafka-client-tls
  brokers:
    config:
      resources:
        storage:
          logDirs:
            capacity: 50Gi
        cpu:
          min: "1500m"
          max: "3"
        memory:
          limit: 2Gi
    roleGroups:
      default:
        replicas: 5
        configOverrides:
          server.properties:
            num.partitions: "27"
            log.segment.bytes: "50000000" # 0.5GB
            log.retention.bytes: "2000000000" # 2 GB. Should keep between 2.0 and 2.5GB
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: kafka-client-tls
spec:
  provider:
    tls:
      clientCertSecretClass: tls
