= stackablectl release
:page-aliases: stable@stackablectl::commands/release.adoc

A release is a bundle of operators of a specific stable version. The stable versions of the operators are tested and
proven to work hand in hand. If you want to install a single individual operator, look at the
xref:commands/operator.adoc[] command.

include::management:stackablectl:partial$commands/release.adoc[]

== Browsing Available Releases

To list the available Stackable releases run the following command:

[source,console]
----
$ stackablectl release list
┌────┬─────────┬──────────────┬─────────────────────────────────────────────────────────────────────────────────┐
│ #  ┆ RELEASE ┆ RELEASE DATE ┆ DESCRIPTION                                                                     │
╞════╪═════════╪══════════════╪═════════════════════════════════════════════════════════════════════════════════╡
│ 1  ┆ 25.3    ┆ 2025-03-24   ┆ The March 2025 release                                                          │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2  ┆ 24.11   ┆ 2024-11-18   ┆ The November 2024 release                                                       │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3  ┆ 24.7    ┆ 2024-07-24   ┆ Security focused release to reduce CVEs and to build product images from source │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4  ┆ 24.3    ┆ 2024-03-20   ┆ Security focused release to improve platform authentication and authorization   │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 5  ┆ 23.11   ┆ 2023-11-30   ┆ Seventh release focusing on PodDisruptionBudgets and graceful shutdown          │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 6  ┆ 23.7    ┆ 2023-07-26   ┆ Sixth release focusing on resources and pod overrides                           │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7  ┆ 23.4    ┆ 2023-05-17   ┆ Fifth release focusing on affinities and product status                         │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 8  ┆ 23.1    ┆ 2023-01-27   ┆ Fourth release focusing on image selection and logging                          │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9  ┆ 22.11   ┆ 2022-11-14   ┆ Third release focusing on resource management                                   │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10 ┆ 22.09   ┆ 2022-09-09   ┆ Second release focusing on security and OpenShift support                       │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 11 ┆ 22.06   ┆ 2022-06-30   ┆ First official release of the Stackable Data Platform                           │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 12 ┆ latest  ┆ 2025-03-24   ┆ Always pointing to the latest stable version of the Stackable Data Platform     │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 13 ┆ dev     ┆ 1970-01-01   ┆ Development versions from main branch. Not stable!                              │
└────┴─────────┴──────────────┴─────────────────────────────────────────────────────────────────────────────────┘
----

Detailed information of a release can be queried with the `stackablectl release describe` command:

[source,console]
----
$ stackablectl release describe 23.7
 RELEASE            23.7
 RELEASE DATE       2023-07-26
 DESCRIPTION        Sixth release focusing on resources and pod overrides
 INCLUDED PRODUCTS   PRODUCT    OPERATOR VERSION
                     airflow    23.7.0
                     commons    23.7.0
                     druid      23.7.0
                     hbase      23.7.0
                     hdfs       23.7.0
                     hive       23.7.0
                     kafka      23.7.0
                     listener   23.7.0
                     nifi       23.7.0
                     opa        23.7.0
                     secret     23.7.0
                     spark-k8s  23.7.0
                     superset   23.7.0
                     trino      23.7.0
                     zookeeper  23.7.0
----

In the output you can see which product operators are included in the specific release.

== Installing Releases

If you want to access a Kubernetes cluster, make sure your https://kubernetes.io/docs/tasks/tools/#kubectl[`kubectl`]
Kubernetes client is configured to interact with the Kubernetes cluster. After that, run the following command:

[source,console]
----
$ stackablectl release install 23.7
Installed product airflow=23.7.0
Installed product commons=23.7.0
Installed product druid=23.7.0
Installed product hbase=23.7.0
Installed product hdfs=23.7.0
Installed product hive=23.7.0
Installed product kafka=23.7.0
Installed product listener=23.7.0
Installed product nifi=23.7.0
Installed product opa=23.7.0
Installed product secret=23.7.0
Installed product spark-k8s=23.7.0
Installed product superset=23.7.0
Installed product trino=23.7.0
Installed product zookeeper=23.7.0
Installed release 23.7
----

If you don't have a Kubernetes cluster available, `stackablectl` can spin up a https://kind.sigs.k8s.io/[kind] or
https://minikube.sigs.k8s.io/docs/[minikube] Kubernetes cluster for you. Based on the type of local cluster you want to
use, ensure you have either `kind` or `minikube` installed on your system. See
xref:commands/demo.adoc#_using_a_local_kubernetes_cluster[here] for more information.

[source,console]
----
$ stackablectl release install 23.7 -c kind
Creating cluster "stackable-data-platform" ...
 ✓ Ensuring node image (kindest/node:v1.26.3) 🖼
 ✓ Preparing nodes 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Joining worker nodes 🚜
Set kubectl context to "kind-stackable-data-platform"
You can now use your cluster with:

kubectl cluster-info --context kind-stackable-data-platform

Have a nice day! 👋
Installed product airflow=23.7.0
Installed product commons=23.7.0
Installed product druid=23.7.0
Installed product hbase=23.7.0
Installed product hdfs=23.7.0
Installed product hive=23.7.0
Installed product kafka=23.7.0
Installed product listener=23.7.0
Installed product nifi=23.7.0
Installed product opa=23.7.0
Installed product secret=23.7.0
Installed product spark-k8s=23.7.0
Installed product superset=23.7.0
Installed product trino=23.7.0
Installed product zookeeper=23.7.0
Installed release 23.7
----

== Upgrading Releases

As described in the xref:home::release-notes.adoc[Upgrade sections of the Release Notes], the upgrade process can be achieved by the following two steps:

. Uninstalling the previous release with `stackablectl release uninstall <RELEASE>`
. Installing the next release with `stackablectl release install <RELEASE>`

The operators maintain their own CRDs and update them automatically on startup, so no manual CRD step is required (see xref:home:concepts:maintenance/crds.adoc[]).

For convenience `stackablectl` also provides an upgrade functionality which executes those steps by itself.
To upgrade a release, run the following command:

[source,console]
----
$ stackablectl release upgrade 25.3

Upgraded to release '25.3'

Use "stackablectl operator installed" to list installed operators.
----

The above command only upgrades the currently installed operators.
To include additional operators in the installation step, use the `--include`/`-i` subcommands and specify the desired operators.

For example
[source,console]
----
$ stackablectl release upgrade 25.3 -i druid -i nifi
----
would upgrade the existing operators as well as install the Stackable operators for Apache Druid and Apache NiFi.

Likewise, operators can be exluded from the upgrade using the `--exclude`/`-e` subcommands.
