---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive
spec:
  image:
    productVersion: 3.1.3
    stackableVersion: "23.4.0-rc2"
  clusterConfig:
    database:
      connString: jdbc:postgresql://postgresql-hive:5432/hive
      user: hive
      password: hive
      dbType: postgres
    s3:
      inline:
        host: minio-trino
        port: 9000
        accessStyle: Path
        credentials:
          secretClass: hive-s3-credentials
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: hive-s3-credentials
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-s3-credentials
  labels:
    secrets.stackable.tech/class: hive-s3-credentials
stringData:
  accessKey: hive
  secretKey: hivehive
