---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 1.5.1
    stackableVersion: "23.4.0-rc2"
  clusterConfig:
    listenerClass: external-unstable
  credentialsSecret: superset-credentials
  mapboxSecret: superset-mapbox-api-key
  nodes:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: adminadmin
  connections.secretKey: thisISaSECRET_1234
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@postgresql-superset/superset
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-mapbox-api-key
type: Opaque
stringData:
  connections.mapboxApiKey: "pk.eyJ1IjoibXVlbGxlcmNlbGluZSIsImEiOiJjbDZwM3llMTAwNGpmM2psdHU0Y21wZHJwIn0.kXFJKBbeyhbwf0z460JcTQ"
# ---
# TODO Use when available (https://github.com/stackabletech/superset-operator/issues/3)
# apiVersion: superset.stackable.tech/v1alpha1
# kind: TrinoConnection
# metadata:
#   name: superset-trino-connection
# spec:
#   superset:
#     name: superset
#   trino:
#     name: trino
