---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  version: 1.5.1-stackable0.2.0
  statsdExporterVersion: v0.22.4
  credentialsSecret: superset-credentials
  nodes:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: SupersetNur 
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: admin
  connections.secretKey: thisISaSECRET_1234
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@postgresql-superset/superset
# ---
# TODO Use when available (https://github.com/stackabletech/superset-operator/issues/3)
# apiVersion: superset.stackable.tech/v1alpha1
# kind: TrinoConnection
# metadata:
#   name: superset-trino-connection
# spec:
#   superset:
#     name: superset
#   trino:
#     name: trino
