---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: hbase
spec:
  version: 2.4.12-stackable0.2.0
  hdfsConfigMapName: hdfs
  zookeeperConfigMapName: hbase-znode
  config:
    hbaseRootdir: /hbase
  masters:
    roleGroups:
      default:
        replicas: 1
    config:
      resources:
        cpu:
          min: "1"
          max: "1"
        memory:
          limit: 3Gi
  regionServers:
    roleGroups:
      default:
        replicas: 2
    config:
      resources:
        cpu:
          min: "2000m"
          max: "4"
        memory:
          limit: 6Gi
  restServers:
    roleGroups:
      default:
        replicas: 1
    config:
      resources:
        cpu:
          min: 250m
          max: 250m
        memory:
          limit: 1500m
