---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: hbase-s3-credentials
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: hbase-s3-credentials
  labels:
    secrets.stackable.tech/class: hbase-s3-credentials
stringData:
  accessKey: demo
  secretKey: demodemo