---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
spec:
  version: 387-stackable0.1.0
  catalogLabelSelector:
    matchLabels:
      trino: trino
  authentication:
    method:
      multiUser:
        userCredentialsSecret:
          name: trino-users
  env:
    - name: HBASE_CONF_DIR
      value: "/stackable/conf/"
  volumeMounts:
    - mountPath: /stackable/conf/hdfs-site.xml
      name: config-volume-hdfs
      subPath: hdfs-site.xml
  volumes:
    - name: config-volume-hbase
      configMap:
        name: hbase-master-default
  opa:
    configMapName: opa
    package: trino
  coordinators:
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: trino-users
type: kubernetes.io/opaque
stringData:
  # admin:admin
  admin: $2y$10$89xReovvDLacVzRGpjOyAOONnayOgDAyIS2nW9bs5DJT98q17Dy5i
  # demo:demo
  demo: $2y$10$mMRoIKfWtAuycEQnKiDCeOlCSYiWkvbs0WsMFLkaSnNO0ZnFKVRXm
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: hive
  labels:
    trino: trino
spec:
  connector:
    hive:
      metastore:
        configMap: hive
      s3:
        inline:
          host: minio-trino
          port: 9000
          accessStyle: Path
          credentials:
            secretClass: trino-s3-credentials
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: trino-s3-credentials
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: trino-s3-credentials
  labels:
    secrets.stackable.tech/class: trino-s3-credentials
stringData:
  accessKey: trino
  secretKey: trinotrino
---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: opa
spec:
  version: 0.41.0-stackable0.1.0
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-opa-bundle
  labels:
    opa.stackable.tech/bundle: "trino"
data:
  trino.rego: |
    package trino

    default allow = false

    allow {
      input.context.identity.user == "admin"
    }

    allow {
      input.context.identity.user == "demo"
    }