---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: keycloak-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: keycloak-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authentication.stackable.tech
    resources:
      - authenticationclasses
    verbs:
      - get
      - list
      - watch
      - create
      - patch
