---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.3
          # Keycloak is running in development mode: https://www.keycloak.org/server/configuration#_starting_keycloak
          # production mode disables HTTP and requires a TLS configuration, which is currently very difficult to configure
          # given that we're running on a NodePort
          args:
            - start
            - --hostname-strict=false
            # - --optimized
            # - --hostname-strict-https=false
            # - --http-enabled=false
            # - –-hostname-strict=false
            # - --hostname-url=https://localhost:8443
            # - --hostname=localhost
            # - --hostname-strict-https=false
            - --https-key-store-file=/tls/keystore.p12
            - --https-key-store-password=changeit
          env:
            # - name: KC_HOSTNAME_STRICT_HTTPS
            #   value: "false"
            # - name: KEYCLOAK_ENABLE_HTTPS
            #   value: "true"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: admin
          ports:
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /realms/master
              port: https
          volumeMounts:
            - name: data
              mountPath: /opt/keycloak/data/
            - name: tls
              mountPath: /tls/
        - name: create-auth-class
          image: docker.stackable.tech/stackable/testing-tools:0.2.0-stackable0.0.0-dev # We need 0.0.0-dev, so we get kubectl
          command:
            - bash
            - -c
            - |
              while :
              do
                echo "Determining Keycloak public reachable address"
                KEYCLOAK_ADDRESS=$(kubectl get svc keycloak -o json | jq -r --argfile endpoints <(kubectl get endpoints keycloak -o json) --argfile nodes <(kubectl get nodes -o json) '($nodes.items[] | select(.metadata.name == $endpoints.subsets[].addresses[].nodeName) | .status.addresses | map(select(.type == "ExternalIP" or .type == "InternalIP")) | min_by(.type) | .address | tostring) + ":" + (.spec.ports[] | select(.name == "https") | .nodePort | tostring)')
                echo "Found Keycloak running at $KEYCLOAK_ADDRESS"

                if [ ! -z "$KEYCLOAK_ADDRESS" ]; then
                  KEYCLOAK_HOSTNAME="$(echo $KEYCLOAK_ADDRESS | grep -oP '^[^:]+')"
                  KEYCLOAK_PORT="$(echo $KEYCLOAK_ADDRESS | grep -oP '[0-9]+$')"

                  cat << EOF | kubectl apply -f -
                    apiVersion: authentication.stackable.tech/v1alpha1
                    kind: AuthenticationClass
                    metadata:
                      name: keycloak
                    spec:
                      provider:
                        oidc:
                          hostname: "$KEYCLOAK_HOSTNAME"
                          port: $KEYCLOAK_PORT
                          rootPath: /realms/master
                          scopes: [openid]
                          tls:
                            verification:
                              none: {}
                              # We can't use this yet, as the cert of Keycloak has no SAN for the NodePort address.
                              # We can switch to this once we include the listener scope in tls certificates.
                              # server:
                              #   caCert:
                              #     secretClass: tls
              EOF
                fi

                sleep 60
              done
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-data
        - name: tls
          ephemeral:
            volumeClaimTemplate:
              metadata:
                annotations:
                  secrets.stackable.tech/class: tls
                  secrets.stackable.tech/format: tls-pkcs12
                  secrets.stackable.tech/format.compatibility.tls-pkcs12.password: changeit
                  secrets.stackable.tech/scope: service=keycloak
              spec:
                storageClassName: secrets.stackable.tech
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: "1"
      serviceAccountName: keycloak-serviceaccount
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
# FIXME: We want a stable Keycloak address that does not change when Keycloak reboots.
# We could simply pick LoadBalancer here, but on-prem clusters often times don't support LBs,
# so the demo would not run on their environments. Additionally, LB addresses often take a while to allocate
# (order of minutes on GCP iirc). So there's no way for us to know whether there's no LB address because it's still
# in progress, or if there's no LB address because it's unsupported.
#
# We should at least make sure to reconcile the AuthClass once Keycloak restarts.
# We could achieve this by letting the keycloak itself propagate it's address instead of a separate Job.
  type: NodePort
  selector:
    app: keycloak
  ports:
    - name: https
      port: 8443
      targetPort: 8443
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
stringData:
  admin: "{{ keycloakAdminPassword }}"
