---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-bundle-trino
  labels:
    opa.stackable.tech/bundle: "true"
data:
  trino.rego: |
    package trino
    import future.keywords.in

    default allow = false

    allow {
      input.context.identity.user in ["alice", "admin"]
    }

    allow {
      input.action.operation == "ImpersonateUser"
      input.action.resource.user.name == input.context.identity.user
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-bundle-druid
  labels:
    opa.stackable.tech/bundle: "true"
data:
  druid.rego: |
    package druid
    import data.bundles.opagroups.admins
    import future.keywords.in
    import future.keywords.if

    default allow = false

    allow if input.user in admins

    allow if input.user == "druid_system"
# A CM like this is created by the setup keycloak Job
# It is used for Druid roles, as we currently need to write them based on the user uuids.
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: opagroups
#   labels:
#     opa.stackable.tech/bundle: "true"
# data:
#   data.json: |
#     {
#       "admins": [
#         "57d3b407-ecc0-4cc1-aaaf-45a63f43b96b",
#         "170b4130-ca4d-417b-b229-f2917d5ab3d1"
#       ]
#     }