apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 2.1.0
    stackableVersion: 23.7.0
  clusterConfig:
    credentialsSecret: superset-credentials
    listenerClass: external-unstable
    authentication:
      - authenticationClass: keycloak
        oidc:
          clientCredentialsSecret: superset-keycloak-client
        userRegistrationRole: Admin # For easier demo purposes
  nodes:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-keycloak-client
stringData:
  clientId: superset
  clientSecret: "supersetsuperset" # "{{ keycloakSupersetClientSecret }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: will-not-be-used # as we use auth/oidc - but maybe we do need it to auto configure the database connection in Superset for the demo
  connections.secretKey: foobarlameinternet # "{{ supersetSecretKey }}"
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@postgresql-superset/superset
