---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
spec:
  image:
    productVersion: "414"
    stackableVersion: 23.7.0
  clusterConfig:
    listenerClass: external-unstable
    tls:
      serverSecretClass: tls
    catalogLabelSelector:
      matchLabels:
        trino: trino
    authentication:
      - authenticationClass: trino-superset-user-for-impersonation
      - authenticationClass: keycloak
        oidc:
          clientCredentialsSecret: trino-keycloak-client
    authorization:
      opa:
        configMapName: opa
        package: trino
  coordinators:
    configOverrides:
      config.properties:
        http-server.authentication.oauth2.principal-field: preferred_username # Works with Keycloak, username did not work (NPE), name returned "Alice Adams"
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpcds
  labels:
    trino: trino
spec:
  connector:
    tpcds: {}
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpch
  labels:
    trino: trino
spec:
  connector:
    tpch: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: trino-keycloak-client
stringData:
  clientId: trino
  clientSecret: "{{ keycloakTrinoClientSecret }}"
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: trino-superset-user-for-impersonation
spec:
  provider:
    static:
      userCredentialsSecret:
        name: trino-superset-user
---
apiVersion: v1
kind: Secret
metadata:
  name: trino-superset-user
type: kubernetes.io/opaque
stringData:
  superset: "{{ trinoSupersetUserPassword }}"
