---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: hbase
spec:
  version: 2.4.12-stackable0.2.0
  hdfsConfigMapName: hdfs
  zookeeperConfigMapName: hbase-znode
  config:
    hbaseRootdir: /hbase
  masters:
    roleGroups:
      default:
        replicas: 1
  regionServers:
    roleGroups:
      default:
        replicas: 2
