---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: hbase
spec:
  image:
    productVersion: 2.4.17
  clusterConfig:
    listenerClass: external-unstable
    hdfsConfigMapName: hdfs
    zookeeperConfigMapName: hbase-znode
  masters:
    roleGroups:
      default:
        replicas: 1
  regionServers:
    roleGroups:
      default:
        replicas: 2
  restServers:
    roleGroups:
      default:
        replicas: 1
