---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  config:
    quorumTlsSecretClass: tls
  servers:
    roleGroups:
      primary:
        replicas: 2
      secondary:
        replicas: 1
  version: 3.8.0-stackable0.99.0
  stopped: false
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hdfs-znode
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hbase-znode
spec:
  clusterRef:
    name: zookeeper