= Services
In this context a (Stackable) service is a running instance of a data product. This is different from the meaning of a Kubernetes service which is an abstract way to expose an application running on a set of pods as a network service.

== List running services
The `stackablectl services` command allows to inspect the running services of the Stackable Data Platform.
Currently you can only get a read-only view of the running services, future versions may allow to e.g. uninstall running services.

An example invocation looks as follows:

[source,console]
----
$ stackablectl services list --all-namespaces
 PRODUCT   NAME         NAMESPACE  ENDPOINTS                                     EXTRA INFOS                          
                                                                                                                      
 hive      hive         default    hive                172.18.0.4:32658                                               
                                   metrics             172.18.0.4:30745                                               
                                                                                                                      
 opa       opa          default    http                http://172.18.0.2:31324                                        
                                                                                                                      
 superset  superset     default    external-superset   http://172.18.0.2:32716   Admin user: admin, password: admin   
                                                                                                                      
 trino     trino        default    coordinator-http    http://172.18.0.5:32128                                        
                                   coordinator-metrics 172.18.0.5:31199                                               
                                   coordinator-https   https://172.18.0.5:32721                                       
                                                                                                                      
 minio     minio-trino  default    http                http://172.18.0.4:31026   Third party service                  
                                   console-http        http://172.18.0.4:30354   Admin user: root, password: rootroot
----

You can also

- Show services in all namespaces
- Redact the passwords from the output in case you want to share the list of services without giving out the admin credentials
- Print the installed product versions

To achieve this you can use the following command:

[source,console]
----
$ stackablectl services list --all-namespaces --redact-credentials --show-versions
----
