---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive
spec:
  version: 3.1.3-stackable0.99.0
  metastore:
    roleGroups:
      default:
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://postgresql-hive:5432/hive
            user: hive
            password: hive
            dbType: postgres