---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  image:
    productVersion: 3.8.1
    stackableVersion: "23.7"
  servers:
    roleGroups:
      default:
        replicas: 1
