---
apiVersion: v1
kind: Job
metadata:
  name: create-hfile-and-import-to-hbase # this jobs create Hfiles first (dedicated Hbase file format with metadata for the HCatalog. Afterwards executing a bulkload to Hbase.
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: merge-config # hbase expects configs from hdfs + hbase in a single directory. Mounting config-maps is only possible to different directories. Therefore, we decided to merge the configs with a InitContainer and provide the configs in a single directory.
      image: docker.stackable.tech/stackable/hbase:2.4.12-stackable0.99.0
      volumeMounts:
        - name: config-volume-hbase
          mountPath: /hbase/conf
        - name: config-volume-hdfs
          mountPath: /hdfs/conf
        - name: merge-config
          mountPath: /stackable/merged-conf
      command: ["bash", "-c", "cp /hbase/conf/* /stackable/merged-conf && cp /hdfs/conf/* /stackable/merged-conf"]
  containers:
    - name: run
      image: docker.stackable.tech/stackable/hbase:2.4.12-stackable0.99.0
      env:
        - name: HBASE_CONF_DIR
          value: "/stackable/merged-conf"
      command: ["bash", "-c", "/stackable/hbase/bin/hbase \
                                org.apache.hadoop.hbase.mapreduce.ImportTsv \
                                -Dimporttsv.separator=, \
                                -Dimporttsv.columns=HBASE_ROW_KEY,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual \
                                -Dimporttsv.bulk.output=hdfs://hdfs/data/hfile \
                                cycling-tripdata hdfs://hdfs/data/raw/demo-cycling-tripdata.csv.gz \
                                && /stackable/hbase/bin/hbase \
                                org.apache.hadoop.hbase.tool.LoadIncrementalHFiles \
                                hdfs://hdfs/data/hfile \
                                cycling-tripdata"]
      volumeMounts:
        - name: merge-config
          mountPath: /stackable/merged-conf
  volumes:
    - name: config-volume-hbase
      configMap:
        name: hbase-demo-master-default
    - name: config-volume-hdfs
      configMap:
        name: hdfs
    - name: merge-config
      emptyDir: {}