---
apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-hbase-load-job
spec:
  template:
    spec:
      containers:
        - name: trigger-hbase-load-job
          image: docker.stackable.tech/stackable/hbase:2.4.12-stackable0.99.0
          command: [ "bash", "-c", "cd /tmp && \
                        && curl -L -O https://repo.stackable.tech/repository/misc/hbase-spark-k8s/hbase-spark-1.0.1-SNAPSHOT.jar \
                        && curl -L -O https://repo.stackable.tech/repository/misc/hbase-spark-k8s/hbase-spark-protocol-shaded-1.0.1-SNAPSHOT.jar \
                        && curl -L -O https://repo.stackable.tech/repository/misc/hbase-spark-k8s/scala-library-2.12.14.jar
                        && curl -L -O https://repo.stackable.tech/repository/misc/hbase-spark-k8s/original-hdfs-hbase-load-1.0.jar \
                    &&  java -jar original-hdfs-hbase-load-1.0.jar \
                    --targetTable ny-taxi-data \
                    --input /hbase/*.parquet \
                    --hbaseSite /stackable/conf/hbase/hbase-site.xml \
                    --hdfsSite /stackable/conf/hdfs/hdfs-site.xml \
                    --coreSite /stackable/conf/hdfs/core-site.xml" ]
          volumeMounts:
            - name: config-volume-hbase
              mountPath: /stackable/conf/hbase
            - name: config-volume-hdfs
              mountPath: /stackable/conf/hdfs
      volumes:
        - name: config-volume-hbase
          configMap:
            name: hbase-demo-master-default
        - name: config-volume-hdfs
          configMap:
            name: hdfs
      restartPolicy: OnFailure
      #todo: check retry limit
