---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-spark-jar-from-nexus-s3
spec:
  template:
    spec:
      containers:
        - name: load-spark-jar-from-nexus-s3
          image: "bitnami/minio:2022-debian-10"
          command: ["bash", "-c", "cd /tmp \
                                    && curl -O https://repo.stackable.tech/repository/misc/hbase-spark-k8s/hbase-spark-demo-1.0.jar \
                                    && mc --insecure alias set minio http://minio-spark-k8s:9000/ demo demodemo && mc cp hbase-spark-demo-1.0.jar minio/demo/jar/"]
      restartPolicy: OnFailure
