---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: hdfs-hbase-load
spec:
  containers:
    - name: run
      image: docker.stackable.tech/stackable/hbase:2.4.12-stackable0.99.0
      volumeMounts:
        - name: config-volume-hbase
          mountPath: /stackable/conf/hbase
        - name: config-volume-hdfs
          mountPath: /stackable/conf/hdfs
  volumes:
    - name: config-volume-hbase
      configMap:
        name: hbase-demo-master-default
    - name: config-volume-hdfs
      configMap:
        name: hdfs