---
apiVersion: batch/v1
kind: Job
metadata:
  name: hbase-prep-job
spec:
  template:
    spec:
      nodeSelector:
        node: "1"
      restartPolicy: Never
      volumes:
        - name: job-jar
          persistentVolumeClaim:
            claimName: hbase-prep-pvc
      containers:
        - name: load-jar
          image: docker.stackable.tech/stackable/tools:0.2.0-stackable0
          env:
            - name: DEST_DIR
              value: "/hbase-job/jar"
          command:
            [
              "bash",
              "-x",
              "-o",
              "pipefail",
              "-c",
              "mkdir -p ${DEST_DIR} && curl -L https://repo.stackable.tech/repository/misc/hbase-spark-k8s/original-hdfs-hbase-load-1.0.jar -o ${DEST_DIR}/original-hdfs-hbase-load-1.0.jar && chown -R stackable:stackable ${DEST_DIR} && chmod -R a=,u=rwX ${DEST_DIR}",
            ]
          volumeMounts:
            - name: job-jar
              mountPath: /hbase
          securityContext:
            runAsUser: 0