---
apiVersion: batch/v1
kind: Job
metadata:
  name: python-test
spec:
  template:
    spec:
      containers:
        - name: load-ny-taxi-data
          image: "bitnami/python:latest"
          command: ["bash", "-c", "pip install pandas, minio && sleep infinity"]
          volumeMounts:
            - name: script
              mountPath: /tmp/script
      volumes:
        - name: script
          configMap:
            name: generate-hash-row-key
      restartPolicy: OnFailure
  backoffLimit: 50
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: generate-hash-row-key
data:
  script.py: |
    from minio import Minio
    import pandas as pd
    import tarfile
    

    LOCAL_FILE_PATH = '/tmp'
    ACCESS_KEY = 'demo'
    SECRET_KEY = 'demodemo'
    MINIO_API_HOST = 'http://demo-minio-hbase:9000'
    BUCKET_NAME = 'demo-bucket'
    OBJECT_NAME = 'events.tgz'
    MINIO_CLIENT = Minio("demo-minio-hbase:9000", access_key=ACCESS_KEY, secret_key=SECRET_KEY, secure=False)

    try:
        MINIO_CLIENT.fget_object(BUCKET_NAME, OBJECT_NAME, '/tmp/events.tgz')
        file = tarfile.open('/tmp/events.tgz')
        file.extractall()
        df = pd.read_csv('/tmp/events.csv')

    finally:
        response.close()
        response.release_conn()