---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-data-to-s3
spec:
  template:
    spec:
      containers:
        - name: load-data-to-s3
          image: docker.io/bitnami/minio-client:2022.8.11-debian-11-r3
          command: ["bash", "-c", "cd /tmp && \
                                   curl -O https://repo.stackable.tech/repository/misc/datasets/retail-store-sales-transactions/events.tgz && \
                                   curl -O https://repo.stackable.tech/repository/misc/datasets/retail-store-sales-transactions/category_tree.tgz && \
                                   curl -O https://repo.stackable.tech/repository/misc/datasets/retail-store-sales-transactions/item_properties_part1.tgz && \
                                   curl -O https://repo.stackable.tech/repository/misc/datasets/retail-store-sales-transactions/item_properties_part2.tgz && \
                                   mc alias set $MINIO_ALIAS $MINIO_SERVER_SCHEME://$MINIO_SERVER_HOST:$MINIO_SERVER_PORT_NUMBER $MINIO_SERVER_ACCESS_KEY $MINIO_SERVER_SECRET_KEY && \
                                   mc mb $MINIO_ALIAS/$MINIO_BUCKET_NAME/tgz && \
                                   mc mb $MINIO_ALIAS/$MINIO_BUCKET_NAME/category_tree && \
                                   mc mb $MINIO_ALIAS/$MINIO_BUCKET_NAME/item_properties && \
                                   mc mb $MINIO_ALIAS/$MINIO_BUCKET_NAME/events && \
                                   mc policy set public $MINIO_ALIAS/$MINIO_BUCKET_NAME && \
                                   mc cp *.tgz $MINIO_ALIAS/$MINIO_BUCKET_NAME/tgz && \
                                   sleep infinity"] #https://www.kaggle.com/datasets/retailrocket/ecommerce-dataset?select=events.csv
          stdin: true
          tty: true
          env:
            - name: MINIO_SERVER_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: hbase-s3-credentials
                  key: accessKey
                  optional: false
            - name: MINIO_SERVER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hbase-s3-credentials
                  key: secretKey
                  optional: false
            - name: MINIO_SERVER_HOST
              value: minio-trino
            - name: MINIO_SERVER_PORT_NUMBER
              value: "9000"
            - name: MINIO_SERVER_SCHEME
              value: http
            - name: MINIO_ALIAS
              value: "demo-minio"
            - name: MINIO_BUCKET_NAME
              value: "demo-bucket"
      restartPolicy: OnFailure
  backoffLimit: 50