---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: hive-s3-secret-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: minio
spec:
  host: minio
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: hive-s3-secret-class
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-s3-secret
  labels:
    secrets.stackable.tech/class: hive-s3-secret-class
stringData:
  accessKey: minio-access-key
  secretKey: minio-secret-key
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-hdfs
spec:
  version: 2.3.9-stackable0.6.0
  hdfs:
    configMap: hdfs
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://hivehdfs-postgresql.default.svc.cluster.local:5432/hivehdfs
            user: hive
            password: hive
            dbType: postgres
          resources:
            storage:
              data:
                capacity: 5Gi
            cpu:
              min: 300m
              max: "2"
            memory:
              limit: 5Gi
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-s3
spec:
  version: 3.1.3-stackable0.2.0
  s3:
    reference: minio
  metastore:
    roleGroups:
      default:
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://hives3-postgresql.default.svc.cluster.local:5432/hives3
            user: hive
            password: hive
            dbType: postgres
          resources:
            storage:
              data:
                capacity: 5Gi
            cpu:
              min: 300m
              max: "2"
            memory:
              limit: 5Gi
