---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: hive-s3-secret-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: minio
spec:
  host: minio
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: hive-s3-secret-class
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-s3-secret
  labels:
    secrets.stackable.tech/class: hive-s3-secret-class
stringData:
  accessKey: trino
  secretKey: trinotrino
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-hdfs
spec:
  image:
    productVersion: 2.3.9
    stackableVersion: "23.4"
  clusterConfig:
    database:
      connString: jdbc:postgresql://hivehdfs-postgresql:5432/hivehdfs
      user: hive
      password: hive
      dbType: postgres
    hdfs:
      configMap: hdfs
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-s3
spec:
  image:
    productVersion: 3.1.3
    stackableVersion: "23.4"
  clusterConfig:
    database:
      connString: jdbc:postgresql://hives3-postgresql:5432/hives3
      user: hive
      password: hive
      dbType: postgres
    s3:
      reference: minio
  metastore:
    roleGroups:
      default:
        replicas: 1
