{
 "title": "Gas measurements",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "R-values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\"\n, AVG(r1) AS \"r1\"\n, AVG(r2) AS \"r2\"\n, AVG(r3) AS \"r3\"\n, AVG(r4) AS \"r4\"\n, AVG(r5) AS \"r5\"\n, AVG(r6) AS \"r6\"\n, AVG(r7) AS \"r7\"\n, AVG(r8) AS \"r8\"\n, AVG(r9) AS \"r9\"\n, AVG(r10) AS \"r10\"\n, AVG(r11) AS \"r11\"\n, AVG(r12) AS \"r12\"\n, AVG(r13) AS \"r13\"\n, AVG(r14) AS \"r14\"\nFROM conditions\nGROUP BY \"time\" ORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Heater Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", avg(heatervoltage) as heatervoltage FROM conditions group by \"time\" order by \"time\""
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", avg(humidity) as humidity FROM conditions group by \"time\" order by \"time\""
    }
   ]
  }
 ]
}