---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: kafka-znode
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka
spec:
  version: 3.3.1-stackable0.1.0
  zookeeperConfigMapName: kafka-znode
  config:
    tls: null
  brokers:
    config:
      resources:
        storage:
          logDirs:
            capacity: 15Gi
        cpu:
          max: 500m
          min: 250m
        memory:
          limit: 2Gi
    roleGroups:
      default:
        replicas: 1
        configOverrides:
          server.properties:
            log.retention.bytes: "4294967296" # 4Gi, as this is for every partition and the demos/users might add multiple topics
