---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: kafka-znode
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: "23.1"
  clusterConfig:
    zookeeperConfigMapName: kafka-znode
    tls: null
  brokers:
    config:
      resources:
        storage:
          logDirs:
            capacity: 15Gi
        cpu:
          max: 500m
          min: 250m
        memory:
          limit: 2Gi
    roleGroups:
      default:
        replicas: 1
        configOverrides:
          server.properties:
            num.partitions: "27"
            # We have
            # 1 brokers
            # and 2 topic (with 27 partitions)
            # 15Gi pvc * 1 brokers = 15Gi total disk size.
            # Lets aim for 50% => 0.5 * 15Gi = 7.5Gi / 54 partitions = 0.138Gi
            log.segment.bytes: "5000000" # 0.05GB
            log.retention.bytes: "10000000" # 0.10 GB. Should keep between 0.10 and 0.15 GB
