---
name: Stackable Release Pipeline

on:
  release:
    types: [published]

jobs:
  release:
    name: Release for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            file-suffix: ""
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            file-suffix: ".exe"
          - target: x86_64-apple-darwin
            os: macos-latest
            file-suffix: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            file-suffix: ""
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: '^1.19.2'
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Prepare Ubuntu env
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y musl-tools
      - name: Prepare Windows env
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@748079362df13449e0a970297aec1550c1c8de2d # tag=v2
        with:
          msystem: MINGW64
          update: true
          install: base-devel mingw-w64-x86_64-go mingw-w64-x86_64-rust
      - name: Build for non-Windows
        if: matrix.os != 'windows-latest'
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # tag=v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo 'Running in MSYS2!'
          cargo build --release --target=${{ matrix.target }}
        shell: msys2 {0}
      - name: Rename binary file
        run: mv target/${{ matrix.target }}/release/stackablectl${{ matrix.file-suffix }} stackablectl-${{ matrix.target }}${{ matrix.file-suffix }}
      - name: Upload Release binaries
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # tag=v1
        with:
          files: stackablectl-${{ matrix.target }}${{ matrix.file-suffix }}
