---
name: Stackable Release Pipeline

on:
  release:
    types: [published]

jobs:
  release:
    name: Release for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            rustFlags: "-C target-feature=+crt-static"
            file-suffix: ""
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            rustFlags: ""
            file-suffix: ".exe"
          - target: x86_64-apple-darwin
            os: macos-latest
            rustFlags: ""
            file-suffix: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            rustFlags: ""
            file-suffix: ""
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # tag=v3
        with:
          go-version: '^1.18.1'
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # tag=v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
        env:
          RUSTFLAGS: "${{ matrix.rustFlags }}"
      - name: Rename binary file
        run: mv target/${{ matrix.target }}/release/stackablectl${{ matrix.file-suffix }} stackablectl-${{ matrix.target }}${{ matrix.file-suffix }}
      - name: Upload Release binaries
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # tag=v1
        with:
          files: stackablectl-${{ matrix.target }}${{ matrix.file-suffix }}
